### ISSUE TITLE
NoSuchMethodError with netty 4.1.0.Final

### ISSUE THREAD

**Issue by arichiardi** [cch1/http.async.client#75]
Hello @cch1,

I bumped into this issue while trying the latest `aleph` version (I know I know..it is still `alpha`), and I wanted to signal here that I receive the following error (using `twitter-api` which is using `http.async.client`).

I am open to `alpha-alpha` testing :smile: 

Thanks for your work by the way!

```
19:57:55.749 [clojure-agent-send-off-pool-1] WARN  twitter-streaming-client.impl - exception during streaming action
java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.setHeader(Ljava/lang/String;Ljava/lang/Object;)V
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.construct(NettyAsyncHttpProvider.java:641)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.buildRequest(NettyAsyncHttpProvider.java:599)
	at com.ning.http.client.providers.netty.NettyConnectListener$Builder.build(NettyConnectListener.java:140)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1031)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:916)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at http.async.client.request$execute_request.invokeStatic(request.clj:226)
	at http.async.client.request$execute_request.doInvoke(request.clj:187)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$apply.invoke(core.clj:641)
	at twitter.request$execute_request_callbacks.invokeStatic(request.clj:41)
	at twitter.request$execute_request_callbacks.invoke(request.clj:36)
	at twitter.core$http_request.invokeStatic(core.clj:105)
	at twitter.core$http_request.invoke(core.clj:87)
	at twitter.api.streaming$statuses_filter.invokeStatic(streaming.clj:19)
	at twitter.api.streaming$statuses_filter.doInvoke(streaming.clj:19)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$apply.invoke(core.clj:641)
	at twitter_streaming_client.impl$create_request_fn$fn__48449.invoke(impl.clj:290)
	at twitter_streaming_client.impl$start_twitter_stream_action.invokeStatic(impl.clj:325)
	at twitter_streaming_client.impl$start_twitter_stream_action.doInvoke(impl.clj:303)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$binding_conveyor_fn$fn__4676.doInvoke(core.clj:1949)
	at clojure.lang.RestFn.applyTo(RestFn.java:146)
	at clojure.lang.Agent$Action.doRun(Agent.java:114)
	at clojure.lang.Agent$Action.run(Agent.java:163)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by arichiardi** [comment]
It looks like `AsyncHttpClient`'s version of netty is lower than aleph's ..welcome to dependency hell :smile:
