### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by zhangshenhua** [cch1/http.async.client#83]
C:\Users\zhang\OneDrive\workspace\clojure\secretary>lein run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Connecting...
ERROR: #error {
 :cause Invalid Status Code 200
 :via
 [{:type java.lang.IllegalStateException
   :message Invalid Status Code 200
   :at [com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 76]}]
 :trace
 [[com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 76]
  [com.ning.http.client.providers.netty.handler.WebSocketProtocol handle WebSocketProtocol.java 100]
  [com.ning.http.client.providers.netty.handler.Processor messageReceived Processor.java 88]
  [org.jboss.netty.channel.SimpleChannelUpstreamHandler handleUpstream SimpleChannelUpstreamHandler.java 70]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 564]
  [org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext sendUpstream DefaultChannelPipeline.java 791]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 296]
  [org.jboss.netty.handler.codec.frame.FrameDecoder unfoldAndFireMessageReceived FrameDecoder.java 459]
  [org.jboss.netty.handler.codec.replay.ReplayingDecoder callDecode ReplayingDecoder.java 536]
  [org.jboss.netty.handler.codec.replay.ReplayingDecoder messageReceived ReplayingDecoder.java 435]
  [org.jboss.netty.channel.SimpleChannelUpstreamHandler handleUpstream SimpleChannelUpstreamHandler.java 70]
  [org.jboss.netty.handler.codec.http.HttpClientCodec handleUpstream HttpClientCodec.java 92]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 564]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 559]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 268]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 255]
  [org.jboss.netty.channel.socket.nio.NioWorker read NioWorker.java 88]
  [org.jboss.netty.channel.socket.nio.AbstractNioWorker process AbstractNioWorker.java 108]
  [org.jboss.netty.channel.socket.nio.AbstractNioSelector run AbstractNioSelector.java 337]
  [org.jboss.netty.channel.socket.nio.AbstractNioWorker run AbstractNioWorker.java 89]
  [org.jboss.netty.channel.socket.nio.NioWorker run NioWorker.java 178]
  [org.jboss.netty.util.ThreadRenamingRunnable run ThreadRenamingRunnable.java 108]
  [org.jboss.netty.util.internal.DeadLockProofWorker$1 run DeadLockProofWorker.java 42]
  [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
  [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
  [java.lang.Thread run nil -1]]}
ERROR: #error {
 :cause Invalid Status Code 200
 :via
 [{:type java.lang.IllegalStateException
   :message Invalid Status Code 200
   :at [com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 76]}]
 :trace
 [[com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 76]
  [com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 29]
  [com.ning.http.client.providers.netty.future.NettyResponseFuture getContent NettyResponseFuture.java 177]
  [com.ning.http.client.providers.netty.future.NettyResponseFuture done NettyResponseFuture.java 214]
  [com.ning.http.client.providers.netty.handler.WebSocketProtocol handle WebSocketProtocol.java 102]
  [com.ning.http.client.providers.netty.handler.Processor messageReceived Processor.java 88]
  [org.jboss.netty.channel.SimpleChannelUpstreamHandler handleUpstream SimpleChannelUpstreamHandler.java 70]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 564]
  [org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext sendUpstream DefaultChannelPipeline.java 791]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 296]
  [org.jboss.netty.handler.codec.frame.FrameDecoder unfoldAndFireMessageReceived FrameDecoder.java 459]
  [org.jboss.netty.handler.codec.replay.ReplayingDecoder callDecode ReplayingDecoder.java 536]
  [org.jboss.netty.handler.codec.replay.ReplayingDecoder messageReceived ReplayingDecoder.java 435]
  [org.jboss.netty.channel.SimpleChannelUpstreamHandler handleUpstream SimpleChannelUpstreamHandler.java 70]
  [org.jboss.netty.handler.codec.http.HttpClientCodec handleUpstream HttpClientCodec.java 92]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 564]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 559]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 268]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 255]
  [org.jboss.netty.channel.socket.nio.NioWorker read NioWorker.java 88]
  [org.jboss.netty.channel.socket.nio.AbstractNioWorker process AbstractNioWorker.java 108]
  [org.jboss.netty.channel.socket.nio.AbstractNioSelector run AbstractNioSelector.java 337]
  [org.jboss.netty.channel.socket.nio.AbstractNioWorker run AbstractNioWorker.java 89]
  [org.jboss.netty.channel.socket.nio.NioWorker run NioWorker.java 178]
  [org.jboss.netty.util.ThreadRenamingRunnable run ThreadRenamingRunnable.java 108]
  [org.jboss.netty.util.internal.DeadLockProofWorker$1 run DeadLockProofWorker.java 42]
  [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
  [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
  [java.lang.Thread run nil -1]]}
ERROR: #error {
 :cause Invalid Status Code 200
 :via
 [{:type java.lang.IllegalStateException
   :message Invalid Status Code 200
   :at [com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 76]}]
 :trace
 [[com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 76]
  [com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 29]
  [com.ning.http.client.providers.netty.future.NettyResponseFuture getContent NettyResponseFuture.java 177]
  [com.ning.http.client.providers.netty.future.NettyResponseFuture done NettyResponseFuture.java 214]
  [com.ning.http.client.providers.netty.handler.WebSocketProtocol handle WebSocketProtocol.java 102]
  [com.ning.http.client.providers.netty.handler.Processor messageReceived Processor.java 88]
  [org.jboss.netty.channel.SimpleChannelUpstreamHandler handleUpstream SimpleChannelUpstreamHandler.java 70]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 564]
  [org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext sendUpstream DefaultChannelPipeline.java 791]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 296]
  [org.jboss.netty.handler.codec.frame.FrameDecoder unfoldAndFireMessageReceived FrameDecoder.java 459]
  [org.jboss.netty.handler.codec.replay.ReplayingDecoder callDecode ReplayingDecoder.java 536]
  [org.jboss.netty.handler.codec.replay.ReplayingDecoder messageReceived ReplayingDecoder.java 435]
  [org.jboss.netty.channel.SimpleChannelUpstreamHandler handleUpstream SimpleChannelUpstreamHandler.java 70]
  [org.jboss.netty.handler.codec.http.HttpClientCodec handleUpstream HttpClientCodec.java 92]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 564]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 559]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 268]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 255]
  [org.jboss.netty.channel.socket.nio.NioWorker read NioWorker.java 88]
  [org.jboss.netty.channel.socket.nio.AbstractNioWorker process AbstractNioWorker.java 108]
  [org.jboss.netty.channel.socket.nio.AbstractNioSelector run AbstractNioSelector.java 337]
  [org.jboss.netty.channel.socket.nio.AbstractNioWorker run AbstractNioWorker.java 89]
  [org.jboss.netty.channel.socket.nio.NioWorker run NioWorker.java 178]
  [org.jboss.netty.util.ThreadRenamingRunnable run ThreadRenamingRunnable.java 108]
  [org.jboss.netty.util.internal.DeadLockProofWorker$1 run DeadLockProofWorker.java 42]
  [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
  [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
  [java.lang.Thread run nil -1]]}
ERROR: #error {
 :cause Invalid Status Code 200
 :via
 [{:type java.lang.IllegalStateException
   :message Invalid Status Code 200
   :at [com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 76]}]
 :trace
 [[com.ning.http.client.ws.WebSocketUpgradeHandler onCompleted WebSocketUpgradeHandler.java 76]
  [com.ning.http.client.providers.netty.handler.WebSocketProtocol onError WebSocketProtocol.java 186]
  [com.ning.http.client.providers.netty.handler.Processor exceptionCaught Processor.java 179]
  [org.jboss.netty.channel.SimpleChannelUpstreamHandler handleUpstream SimpleChannelUpstreamHandler.java 112]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 564]
  [org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext sendUpstream DefaultChannelPipeline.java 791]
  [org.jboss.netty.handler.codec.frame.FrameDecoder exceptionCaught FrameDecoder.java 377]
  [org.jboss.netty.channel.SimpleChannelUpstreamHandler handleUpstream SimpleChannelUpstreamHandler.java 112]
  [org.jboss.netty.handler.codec.http.HttpClientCodec handleUpstream HttpClientCodec.java 92]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 564]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 559]
  [org.jboss.netty.channel.Channels fireExceptionCaught Channels.java 525]
  [org.jboss.netty.channel.AbstractChannelSink exceptionCaught AbstractChannelSink.java 48]
  [org.jboss.netty.channel.DefaultChannelPipeline notifyHandlerException DefaultChannelPipeline.java 658]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 566]
  [org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext sendUpstream DefaultChannelPipeline.java 791]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 296]
  [org.jboss.netty.handler.codec.frame.FrameDecoder unfoldAndFireMessageReceived FrameDecoder.java 459]
  [org.jboss.netty.handler.codec.replay.ReplayingDecoder callDecode ReplayingDecoder.java 536]
  [org.jboss.netty.handler.codec.replay.ReplayingDecoder messageReceived ReplayingDecoder.java 435]
  [org.jboss.netty.channel.SimpleChannelUpstreamHandler handleUpstream SimpleChannelUpstreamHandler.java 70]
  [org.jboss.netty.handler.codec.http.HttpClientCodec handleUpstream HttpClientCodec.java 92]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 564]
  [org.jboss.netty.channel.DefaultChannelPipeline sendUpstream DefaultChannelPipeline.java 559]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 268]
  [org.jboss.netty.channel.Channels fireMessageReceived Channels.java 255]
  [org.jboss.netty.channel.socket.nio.NioWorker read NioWorker.java 88]
  [org.jboss.netty.channel.socket.nio.AbstractNioWorker process AbstractNioWorker.java 108]
  [org.jboss.netty.channel.socket.nio.AbstractNioSelector run AbstractNioSelector.java 337]
  [org.jboss.netty.channel.socket.nio.AbstractNioWorker run AbstractNioWorker.java 89]
  [org.jboss.netty.channel.socket.nio.NioWorker run NioWorker.java 178]
  [org.jboss.netty.util.ThreadRenamingRunnable run ThreadRenamingRunnable.java 108]
  [org.jboss.netty.util.internal.DeadLockProofWorker$1 run DeadLockProofWorker.java 42]
  [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
  [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
  [java.lang.Thread run nil -1]]}
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Invalid Status Code 200, compiling:(C:\Users\zhang\AppData\Local\Temp\form-init6990636374482494791.clj:1:108)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$init_opt.invokeStatic(main.clj:280)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Invalid Status Code 200
        at com.ning.http.client.providers.netty.future.NettyResponseFuture.done(NettyResponseFuture.java:220)
        at com.ning.http.client.providers.netty.handler.WebSocketProtocol.handle(WebSocketProtocol.java:102)
        at com.ning.http.client.providers.netty.handler.Processor.messageReceived(Processor.java:88)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Invalid Status Code 200
        at com.ning.http.client.ws.WebSocketUpgradeHandler.onCompleted(WebSocketUpgradeHandler.java:76)
        at com.ning.http.client.ws.WebSocketUpgradeHandler.onCompleted(WebSocketUpgradeHandler.java:29)
        at com.ning.http.client.providers.netty.future.NettyResponseFuture.getContent(NettyResponseFuture.java:177)
        at com.ning.http.client.providers.netty.future.NettyResponseFuture.done(NettyResponseFuture.java:214)
        ... 25 more

C:\Users\zhang\OneDrive\workspace\clojure\secretary>

**Comment by brunchboy** [comment]
This looks like an expected result for a project that uses [slf4j](http://www.slf4j.org/manual.html) to configure logging. My own library does this, but I have the following sentence in my README, so it would probably be a good idea to add something similar to this project README:

> Beat link uses [slf4j](http://www.slf4j.org/manual.html) to allow you to integrate it with whatever Java logging framework your project is using, so you will need to include the appropriate slf4j binding on your class path.

In any case, @zhangshenhua if you follow the above links to the slf4j documentation, you will see that exact message and how to configure your class path to fix it.
